language: node_js
node_js:
  - "5"
  - "6"
  - "7"
before_install: 
  - npm install -g heroku-cli
install: npm install
before_script: npm install -g angular-cli
script: npm run build
branches:
  only:
  - master
after_script: 
  - chmod +x heroku_deploy.sh
  - ./heorku_deploy.sh