language: node_js
node_js:
  - "6"
before_install:
  - npm install -g @angular/cli
install: npm install
#before_script: npm install -g angular-cli
#refer package.json for postinstall script
#script: npm run build
branches:
  only:
  - master
after_script: 
  - chmod +x heroku_deploy.sh
  - ./heroku_deploy.sh